syntax = "proto3";
package lumiwaveprotocol.lumiwaveprotocol.v1;

import "amino/amino.proto";
import "gogoproto/gogo.proto";
import "lumiwaveprotocol/lumiwaveprotocol/v1/params.proto";

option go_package = "github.com/LumiWave/lumiwave-protocol/x/lumiwaveprotocol/types";

// GenesisState defines the lumiwaveprotocol module's genesis state.
message GenesisState {
  // params defines all the parameters of the module.
  Params params = 1 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}
