# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: lumiwave-protocold
    main: ./cmd/lumiwave-protocold/
    binary: lumiwave-protocold

    env:
      - CGO_ENABLED=1

    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=lumiwave-protocol
      - -X github.com/cosmos/cosmos-sdk/version.AppName=lumiwave-protocold
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats: [tar.gz]
    files:
      - none*
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).