version: 1
validation: sovereign
# 1. 기본 단위를 alwp로 설정 (atto-lwp, 10^-18)
default_denom: alwp
# 2. 메타데이터 추가 (LWP 심볼과 소수점 6자리 정의)
genesis:
  app_state:
    bank:
      denom_metadata:
        - description: "The native coin of LumiWave Protocol"
          denom_units:
            - denom: alwp
              exponent: 0
              aliases: ["attolwp"]
            - denom: LWP
              exponent: 6
          base: alwp
          display: LWP
          name: "LumiWave Protocol Coin"
          symbol: LWP
    mint:
      params:
        mint_denom: "alwp"
        inflation_max: "0.344100000000000000" # 인플레이션 최대치 0
        inflation_min: "0.000000000000000000" # 인플레이션 최소치 0
        inflation_rate_change: "0.344100000000000000"
        goal_bonded: "0.670000000000000000"
        blocks_per_year: "6307200" # test : 12s, real : 6307200
      minter:
        inflation: "0.344100000000000000" # 현재 인플레이션율 0
    staking:
      params:
        bond_denom: "alwp" # 스테이킹 단위도 alwp로 일치
    distribution:
      params:
        community_tax: "0.917000000000000000"
        base_proposer_reward: "0.000000000000000000"
        bonus_proposer_reward: "0.000000000000000000"
        withdraw_addr_enabled: true
accounts: 
# 초기 유통 물량 (1억 LWP)
  - name: pdx-test-yangjae
    coins: ["770075466000000000000000000alwp"]
  - name: pdx-test-faucet
    coins:
      - 100000000000000000000000alwp
client:
  openapi:
    path: docs/static/openapi.json
faucet:
  name: pdx-test-faucet
  coins: ["5000000000000000000000000alwp"]
  tx_fee: "10000000000000000alwp" # 약 0.01 LWP
validators:
- name: pdx-test-yangjae
  bonded: "500000000000000000000000alwp"
  app:
    minimum-gas-prices: "1000000000alwp"
    pruning: "custom"
    pruning-keep-recent: "100"
    pruning-interval: "10"
    pruning-keep-every: "0"
    state-sync:
      snapshot-interval: "1000"
    api:
      enable: true
      swagger: true
  config:
    moniker: "pdx-validator"
    tx_index:
      indexer: "null"
    instrumentation:
      prometheus: true
    consensus:
      # 블록 생성 간격을 결정하는 핵심 파라미터들입니다.
      timeout_propose: "3s"
      timeout_prevote: "1s"
      timeout_precommit: "1s"
      timeout_commit: "5s"  # 여기서 실제 블록 생성 주기가 약 5~6초로 결정됩니다.

